### ISSUE TITLE
Needs more issues

### ISSUE THREAD

**Issue by neobrain** [neobrain/test#3]
How about adding more issues?

**Comment by neobrain** [comment]
Please don't create pointless issues like this.

**Comment by Subv** [comment]
What happens if i comment on a closed issue?

**Comment by neobrain** [comment]
I don't know, you tell me?

**Comment by neobrain** [comment]
Hi!

**Comment by neobrain** [comment]
bla

**Comment by Subv** [comment]
abl

**Comment by neobrain** [comment]
more bla.

**Comment by neobrain** [comment]
Ok, time to reopen this.

**Comment by Subv** [comment]
Testing again

**Comment by shinyquagsire23** [comment]
Obligatory random comment after the issue gets closed
